USER_NAME := dejevin

DEFERRED_EXEC_ENABLE = yes
COMMAND_ENABLE = yes
BACKLIGHT_ENABLE = no
KEY_LOCK_ENABLE = no
MOUSEKEY_ENABLE = yes

DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_MACRO_NO_NESTING = true

DEBOUNCE_TYPE = asym_eager_defer_pk
